package agent

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/rowsafe/rowsafe/protocol"
)

func TestDrillDirGuards(t *testing.T) {
	a := &Agent{cfg: Config{DrillDir: "/var/lib/rowsafe/drills"}}
	dir, err := a.drillDir("task_abc123", "/var/lib/postgresql/18/main")
	if err != nil || dir != "/var/lib/rowsafe/drills/task_abc123" {
		t.Fatalf("got %q, %v", dir, err)
	}
	for _, bad := range []string{"../../postgresql/18/main", "..", "a/b", "task.1"} {
		if _, err := a.drillDir(bad, "/var/lib/postgresql/18/main"); err == nil {
			t.Errorf("task id %q should be rejected", bad)
		}
	}
	// A drill directory must never overlap the production data directory.
	if _, err := a.drillDir("task_x", "/var/lib/rowsafe/drills/task_x"); err == nil {
		t.Error("drill dir equal to the data dir should be rejected")
	}
	if _, err := a.drillDir("task_x", "/var/lib/rowsafe"); err == nil {
		t.Error("drill dir inside the data dir should be rejected")
	}
	if _, err := a.drillDir("task_x", "/var/lib/rowsafe/drills/task_x/data"); err == nil {
		t.Error("data dir inside the drill dir should be rejected")
	}
}

func TestDrillConfIsIsolated(t *testing.T) {
	conf := drillConf(scratchSpec{Port: 55432, SocketDir: "/var/lib/rowsafe/drills/t/socket", Major: 18})
	for _, want := range []string{
		"listen_addresses = ''", "archive_mode = 'off'", "hot_standby = 'off'",
		"unix_socket_directories = '/var/lib/rowsafe/drills/t/socket'",
		"shared_preload_libraries = ''", "max_worker_processes = '0'", "max_logical_replication_workers = '0'",
		"default_transaction_read_only = 'on'", "event_triggers = 'off'",
	} {
		if !strings.Contains(conf, want) {
			t.Errorf("drill config missing %q", want)
		}
	}
	if strings.Contains(conf, "stats_temp_directory") {
		t.Error("stats_temp_directory does not exist on PostgreSQL 15+ and would stop the server from starting")
	}
	old := drillConf(scratchSpec{Port: 55432, SocketDir: "/s", Major: 14})
	if strings.Contains(old, "event_triggers") || !strings.Contains(old, "stats_temp_directory = 'pg_stat_tmp'") {
		t.Errorf("PostgreSQL 14 settings wrong:\n%s", old)
	}
}

// parseConf applies postgresql.conf semantics that matter here: later lines
// override earlier ones.
func parseConf(s string) map[string]string {
	out := map[string]string{}
	for _, line := range strings.Split(s, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		name, value, ok := strings.Cut(line, "=")
		if ok {
			out[strings.TrimSpace(name)] = strings.Trim(strings.TrimSpace(value), "'")
		}
	}
	return out
}

// The restored postgresql.auto.conf carries production's ALTER SYSTEM
// settings; what the drill appends must win over all of them.
func TestDrillAutoConfOverrideWins(t *testing.T) {
	restored := `# Do not edit this file manually!
archive_mode = 'on'
archive_command = '/usr/bin/pgbackrest --config=/etc/rowsafe/pgbackrest/tvhub.conf --stanza=tvhub archive-push %p'
listen_addresses = '*'
port = '5432'
shared_buffers = '16GB'
max_connections = '500'
hot_standby = 'on'
ssl = 'on'
external_pid_file = '/var/run/postgresql/18-main.pid'

# Recovery settings generated by pgBackRest restore on 2026-09-24 00:29:29
archive_mode = 'off'
restore_command = 'pgbackrest --config=/etc/rowsafe/pgbackrest/tvhub.conf --pg1-path=/d --stanza=tvhub archive-get %f "%p"'
`
	restored += "shared_preload_libraries = 'pg_cron,pg_net,timescaledb'\nmax_worker_processes = '16'\n"
	spec := scratchSpec{Port: 55432, SocketDir: "/var/lib/rowsafe/drills/t/socket", Major: 18}
	got := parseConf(restored + drillAutoConfOverride(spec))
	for name, want := range map[string]string{
		"archive_mode": "off", "archive_command": "", "listen_addresses": "", "port": "55432",
		"unix_socket_directories": "/var/lib/rowsafe/drills/t/socket", "shared_buffers": "128MB",
		"max_connections": "20", "hot_standby": "off", "ssl": "off", "external_pid_file": "",
		"max_wal_senders": "0", "cluster_name": "rowsafe-drill", "shared_preload_libraries": "",
		"max_worker_processes": "0", "max_logical_replication_workers": "0",
	} {
		if got[name] != want {
			t.Errorf("%s = %q, want %q", name, got[name], want)
		}
	}
	if !strings.Contains(got["restore_command"], "archive-get") {
		t.Error("restore_command from pgBackRest must survive")
	}

	// The fallback start appends a second block with production's
	// libraries; everything else stays locked down.
	spec.Preload = "pg_cron,timescaledb"
	got = parseConf(restored + drillAutoConfOverride(scratchSpec{Port: 55432, SocketDir: "/s", Major: 18}) + drillAutoConfOverride(spec))
	if got["shared_preload_libraries"] != "pg_cron,timescaledb" || got["max_worker_processes"] != "0" ||
		got["cron.launch_active_jobs"] != "off" || got["timescaledb.max_background_workers"] != "0" {
		t.Errorf("fallback settings: %v", got)
	}
}

func TestDrillSocketPathLimit(t *testing.T) {
	a := &Agent{cfg: Config{DrillDir: "/var/lib/rowsafe/drills", DrillPort: 55432}}
	dir, _ := a.drillDir("task_7fz3q9m2k1x0p", "/var/lib/postgresql/18/main")
	if n := len(dir + "/socket/.s.PGSQL.55432"); n > maxSocketPath {
		t.Errorf("default layout socket path is %d bytes", n)
	}
}

type fakeRunner struct {
	mu    sync.Mutex
	calls [][]string
}

func (f *fakeRunner) Run(_ context.Context, name string, args ...string) ([]byte, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.calls = append(f.calls, append([]string{name}, args...))
	return nil, nil
}

func TestCleanupStaleDrillsOnlyRemovesMarkedDirs(t *testing.T) {
	root := t.TempDir()
	drills := filepath.Join(root, "drills")
	mkDrill := func(name string, pid int) string {
		data := filepath.Join(drills, name, "data")
		if err := os.MkdirAll(data, 0o700); err != nil {
			t.Fatal(err)
		}
		os.WriteFile(filepath.Join(drills, name, drillMarker), []byte(name+"\n"), 0o600)
		os.WriteFile(filepath.Join(data, "PG_VERSION"), []byte("18\n"), 0o600)
		os.WriteFile(filepath.Join(data, "postmaster.pid"), []byte(fmt.Sprintf("%d\n%s\n", pid, data)), 0o600)
		return data
	}
	// A still-running scratch postmaster (stand-in: a process with -D data).
	liveData := filepath.Join(drills, "task_live", "data")
	live := exec.Command("sh", "-c", "sleep 60", "postgres", "-D", liveData)
	if err := live.Start(); err != nil {
		t.Fatal(err)
	}
	defer live.Process.Kill()
	mkDrill("task_live", live.Process.Pid)
	// After a reboot a stale postmaster.pid can name an unrelated process,
	// possibly the production postmaster. Here: this test process.
	staleData := mkDrill("task_stale", os.Getpid())
	// Not ours: no marker. And a symlink pointing at "production".
	foreign := filepath.Join(drills, "main", "base")
	os.MkdirAll(foreign, 0o700)
	prod := filepath.Join(root, "prod", "main")
	os.MkdirAll(prod, 0o700)
	os.Symlink(filepath.Join(root, "prod"), filepath.Join(drills, "task_link"))

	fr := &fakeRunner{}
	a := &Agent{cfg: Config{DrillDir: drills, PGBinDir: "/usr/lib/postgresql/%d/bin"}, runner: fr,
		log: slog.New(slog.NewTextHandler(io.Discard, nil))}
	a.cleanupStaleDrills()

	for _, name := range []string{"task_live", "task_stale"} {
		if _, err := os.Stat(filepath.Join(drills, name)); !os.IsNotExist(err) {
			t.Errorf("%s should be removed", name)
		}
	}
	if _, err := os.Stat(foreign); err != nil {
		t.Error("a directory without the drill marker must be left alone")
	}
	if _, err := os.Stat(prod); err != nil {
		t.Error("a symlink target must never be touched")
	}
	stopLive := "/usr/lib/postgresql/18/bin/pg_ctl -D " + liveData + " -m immediate -w -t 60 stop"
	var calls []string
	for _, c := range fr.calls {
		calls = append(calls, strings.Join(c, " "))
	}
	if !slices.Contains(calls, stopLive) {
		t.Errorf("the running scratch postmaster was not stopped; calls = %v", calls)
	}
	if runtime.GOOS == "linux" {
		// The fake pg_ctl did not stop the stand-in, so the verified
		// fallback must have signalled it.
		if err := live.Wait(); err == nil {
			t.Error("live stand-in should have been killed")
		}
		for _, c := range calls {
			if strings.Contains(c, staleData) {
				t.Errorf("pg_ctl must not be pointed at a stale pid file whose PID is another process: %s", c)
			}
		}
	}
}

func TestInterruptedTaskIsReportedAfterRestart(t *testing.T) {
	var got protocol.CompleteRequest
	var path string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		path = r.URL.Path
		json.NewDecoder(r.Body).Decode(&got)
		w.WriteHeader(http.StatusNoContent)
	}))
	defer srv.Close()
	a := &Agent{cfg: Config{StateDir: t.TempDir()}, client: newControlClient(srv.URL, "rsa_x"),
		log: slog.New(slog.NewTextHandler(io.Discard, nil))}

	a.saveRunning(runningTask{ID: "task_abc", Type: "drill", StartedAt: time.Now()})
	a.reportInterrupted(context.Background())
	if path != "/v1/agent/tasks/task_abc/complete" || got.Status != protocol.StatusFailed ||
		!strings.Contains(got.Error, "agent stopped") {
		t.Errorf("reported %s %+v", path, got)
	}
	if _, err := os.Stat(a.runningPath()); !os.IsNotExist(err) {
		t.Error("running-task state should be cleared once reported")
	}

	// An outcome that could not be delivered before a shutdown is resent as is.
	done := protocol.CompleteRequest{Status: protocol.StatusSucceeded, Log: "backup ok"}
	a.saveRunning(runningTask{ID: "task_def", Type: "backup", StartedAt: time.Now(), Report: &done})
	a.reportInterrupted(context.Background())
	if path != "/v1/agent/tasks/task_def/complete" || got.Status != protocol.StatusSucceeded || got.Log != "backup ok" {
		t.Errorf("reported %s %+v", path, got)
	}
}

func TestCompareDatabases(t *testing.T) {
	source := []protocol.DBInfo{{Name: "app", Tables: 66}, {Name: "postgres", Tables: 0}, {Name: "gone", Tables: 3}, {Name: "drift", Tables: 5}}
	restored := []protocol.DBInfo{{Name: "app", Tables: 66}, {Name: "postgres", Tables: 0}, {Name: "drift", Tables: 4}}
	out, failures, warnings := compareDatabases(source, restored)
	if len(out) != 4 {
		t.Fatalf("want 4 databases, got %d", len(out))
	}
	if len(failures) != 1 || !strings.Contains(failures[0], `"gone"`) {
		t.Errorf("failures = %v", failures)
	}
	if len(warnings) != 1 || !strings.Contains(warnings[0], `"drift"`) {
		t.Errorf("warnings = %v", warnings)
	}

	_, failures, _ = compareDatabases([]protocol.DBInfo{{Name: "app", Tables: 10}}, []protocol.DBInfo{{Name: "app", Tables: 0}})
	if len(failures) != 1 {
		t.Error("an empty restore of a non-empty database must fail")
	}
}

func TestAlterSystemQuoting(t *testing.T) {
	stmt, err := alterSystem("archive_command", "a 'quoted' %p")
	if err != nil {
		t.Fatal(err)
	}
	if stmt != `ALTER SYSTEM SET "archive_command" = 'a ''quoted'' %p'` {
		t.Errorf("got %s", stmt)
	}
	if stmt, _ := alterSystem("archive_library", ""); stmt != `ALTER SYSTEM RESET "archive_library"` {
		t.Errorf("got %s", stmt)
	}
	for _, bad := range []string{"a\\b", "a\nb"} {
		if _, err := alterSystem("archive_command", bad); err == nil {
			t.Errorf("value %q should be refused", bad)
		}
	}
}
