package agent

import (
	"context"
	"errors"
	"log/slog"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/rowsafe/rowsafe/internal/pgbackrest"
	"github.com/rowsafe/rowsafe/protocol"
)

// fakeOps plays PostgreSQL, the root helper and pgBackRest for rewinds in
// place. Directories and renames are real (in a temp dir); "running" is
// which data directory the fake postmaster serves.
type fakeOps struct {
	mu      sync.Mutex
	f       inPlaceFacts
	live    bool   // PostgreSQL runs from f.DataDir
	liveDir string // what the running PostgreSQL's data directory holds (its marker)
	private bool   // the private recovery postmaster runs
	calls   []string
	fail    map[string]error // step -> error: stop, start, restore, recover, ready, stoplocal, repo, facts
	failN   map[string]int   // how many times a step fails (0: always)
	free    int64
}

func newFakeOps(dataDir string) *fakeOps {
	return &fakeOps{f: inPlaceFacts{DataDir: dataDir, Major: 18, SizeBytes: 1 << 20, ConfigFile: "/etc/postgresql/18/main/postgresql.conf",
		HbaFile: "/etc/postgresql/18/main/pg_hba.conf", IdentFile: "/etc/postgresql/18/main/pg_ident.conf"},
		live: true, liveDir: "ORIGINAL", fail: map[string]error{}, failN: map[string]int{}, free: 1 << 40}
}

func (o *fakeOps) failing(step string) error {
	err := o.fail[step]
	if err == nil {
		return nil
	}
	if n, ok := o.failN[step]; ok {
		if n <= 0 {
			return nil
		}
		o.failN[step] = n - 1
	}
	return err
}

func (o *fakeOps) call(s string) { o.calls = append(o.calls, s) }

func marker(dir string) string {
	b, _ := os.ReadFile(filepath.Join(dir, "MARKER"))
	return string(b)
}

func (o *fakeOps) facts(context.Context, protocol.DatabaseSpec) (inPlaceFacts, error) {
	o.mu.Lock()
	defer o.mu.Unlock()
	return o.f, o.failing("facts")
}

func (o *fakeOps) helper(_ context.Context, action string, _ int, _ string) error {
	o.mu.Lock()
	defer o.mu.Unlock()
	o.call(action)
	if err := o.failing(action); err != nil {
		return err
	}
	switch action {
	case helperStop:
		o.live = false
	case helperStart:
		if !exists(filepath.Join(o.f.DataDir, "MARKER")) {
			return errors.New("systemctl start failed: no data directory")
		}
		o.live, o.liveDir = true, marker(o.f.DataDir)
	}
	return nil
}

func (o *fakeOps) running(dataDir string) bool {
	o.mu.Lock()
	defer o.mu.Unlock()
	return dataDir == o.f.DataDir && (o.live || o.private)
}

func (o *fakeOps) repo(context.Context, protocol.DatabaseSpec, string) error {
	o.mu.Lock()
	defer o.mu.Unlock()
	o.call("repo")
	return o.failing("repo")
}

func (o *fakeOps) restore(_ context.Context, _ protocol.DatabaseSpec, opts pgbackrest.RestoreOptions) ([]byte, error) {
	o.mu.Lock()
	defer o.mu.Unlock()
	o.call("restore " + opts.Type + " " + opts.Target)
	if opts.ArchiveOff || opts.TablespaceDir != "" {
		return nil, errors.New("an in-place restore must keep production's archiving and paths")
	}
	os.WriteFile(filepath.Join(opts.DataDir, "PARTIAL"), nil, 0o600)
	if err := o.failing("restore"); err != nil {
		return []byte("ERROR: [039]: something"), err
	}
	os.WriteFile(filepath.Join(opts.DataDir, "MARKER"), []byte("RESTORED"), 0o600)
	os.WriteFile(filepath.Join(opts.DataDir, "postgresql.auto.conf"), []byte("# Do not edit this file manually!\narchive_command = 'old from backup'\n\n"+
		pgbackrestRecoveryHeader+" on 2026-09-24 14:10:00\nrestore_command = 'pgbackrest archive-get %f \"%p\"'\nrecovery_target_time = '"+opts.Target+"'\n"), 0o600)
	return []byte("restore command end: completed successfully"), nil
}

func (o *fakeOps) recover(_ context.Context, r privateRecovery) (*time.Time, error) {
	o.mu.Lock()
	defer o.mu.Unlock()
	if r.ConfigFile != o.f.ConfigFile || filepath.Base(r.SocketDir) != "inplace" {
		return nil, errors.New("private recovery set up wrong")
	}
	if exists(filepath.Join(r.DataDir, "recovery.signal")) {
		// A move to a new timeline: recovery to the end of the local WAL.
		o.call("timeline")
		auto, _ := os.ReadFile(filepath.Join(r.DataDir, "postgresql.auto.conf"))
		if !strings.Contains(string(auto), "recovery_target_timeline = 'current'") || !strings.Contains(string(auto), "archive-get %f") {
			return nil, errors.New("new timeline set up wrong:\n" + string(auto))
		}
		return nil, o.failing("timeline")
	}
	o.call("recover")
	if err := o.failing("recover"); err != nil {
		o.private = true // left running: the rollback must stop it
		return nil, err
	}
	t := time.Date(2026, 9, 24, 14, 3, 59, 0, time.UTC)
	return &t, nil
}

func (o *fakeOps) stopLocal(string, int) error {
	o.mu.Lock()
	defer o.mu.Unlock()
	o.call("stoplocal")
	if err := o.failing("stoplocal"); err != nil {
		return err
	}
	o.private = false
	return nil
}

func (o *fakeOps) waitReady(context.Context, protocol.DatabaseSpec, string, time.Duration) error {
	o.mu.Lock()
	defer o.mu.Unlock()
	o.call("ready")
	if err := o.failing("ready"); err != nil {
		return err
	}
	if !o.live {
		return errors.New("not running")
	}
	return nil
}

func (o *fakeOps) freeBytes(string) (int64, error) { return o.free, nil }

type inPlaceEnv struct {
	t       *testing.T
	a       *Agent
	ops     *fakeOps
	dataDir string
	db      protocol.DatabaseSpec
}

func newInPlaceEnv(t *testing.T) *inPlaceEnv {
	root := t.TempDir()
	parent := filepath.Join(root, "18")
	dataDir := filepath.Join(parent, "main")
	must(t, os.MkdirAll(dataDir, 0o700))
	must(t, os.WriteFile(filepath.Join(dataDir, "MARKER"), []byte("ORIGINAL"), 0o600))
	must(t, os.WriteFile(filepath.Join(dataDir, "postgresql.auto.conf"), []byte("# Do not edit this file manually!\n"+
		"archive_mode = 'on'\narchive_command = '/usr/bin/pgbackrest --stanza=app archive-push %p'\narchive_timeout = '60'\n"+
		"restore_command = 'left over from an earlier restore'\n"), 0o600))
	allow := filepath.Join(root, "restart-allowed")
	must(t, os.WriteFile(allow, []byte("5432 postgresql@18-main.service\n"), 0o644))
	helperPath := filepath.Join(root, "rowsafe-pg-restart")
	must(t, os.WriteFile(helperPath, []byte("#!/bin/sh\n# actions: restart stop start\n"), 0o755))
	must(t, os.MkdirAll(filepath.Join(root, "restart"), 0o700))
	ops := newFakeOps(dataDir)
	short, err := os.MkdirTemp("/tmp", "rw") // macOS temp dirs are too long for a socket path
	must(t, err)
	t.Cleanup(func() { os.RemoveAll(short) })
	a := &Agent{cfg: Config{StateDir: filepath.Join(root, "state"), RewindDir: short, RestartAllowFile: allow,
		RestartHelper: helperPath, RestartDir: filepath.Join(root, "restart"), PGUser: "postgres",
		PgBackRestBin: "/usr/bin/pgbackrest", ConfigDir: "/etc/rowsafe/pgbackrest"},
		log: slog.New(slog.DiscardHandler), rewindOps: ops}
	oldStop, oldPoll := inPlaceStopWait, inPlacePoll
	inPlaceStopWait, inPlacePoll = 50*time.Millisecond, time.Millisecond
	t.Cleanup(func() { inPlaceStopWait, inPlacePoll = oldStop, oldPoll })
	return &inPlaceEnv{t: t, a: a, ops: ops, dataDir: dataDir,
		db: protocol.DatabaseSpec{ID: "db_1", Name: "shop", Stanza: "shop", Port: 5432, SocketDir: "/var/run/postgresql"}}
}

var target1404 = time.Date(2026, 9, 24, 14, 4, 0, 0, time.UTC)

func (e *inPlaceEnv) params(id string) protocol.RewindInPlaceParams {
	return protocol.RewindInPlaceParams{RewindID: id, KeepDays: 7,
		Target: protocol.RewindTarget{Time: &target1404, BackupSet: "20260924-010000F"}}
}

func (e *inPlaceEnv) rewind(id string) (*protocol.RewindInPlaceResult, error, string) {
	tl := &taskLog{}
	res, err := e.a.rewindInPlace(e.t.Context(), e.db, e.params(id), tl)
	return res, err, tl.String()
}

// siblings lists the data directory's parent (names only).
func (e *inPlaceEnv) siblings() []string {
	entries, _ := os.ReadDir(filepath.Dir(e.dataDir))
	var out []string
	for _, x := range entries {
		out = append(out, x.Name())
	}
	return out
}

// original checks production runs the original data, with nothing left over.
func (e *inPlaceEnv) original(what string) {
	e.t.Helper()
	if marker(e.dataDir) != "ORIGINAL" || !e.ops.live || e.ops.liveDir != "ORIGINAL" || e.ops.private {
		e.t.Fatalf("%s: data %q, live %v (%q), private %v", what, marker(e.dataDir), e.ops.live, e.ops.liveDir, e.ops.private)
	}
	if s := e.siblings(); !slices.Equal(s, []string{"main"}) {
		e.t.Fatalf("%s: left behind %v", what, s)
	}
	if _, ok := e.a.rewindState().get("rw_1"); ok {
		e.t.Fatalf("%s: the rewind is still recorded", what)
	}
}

func TestRewindInPlaceUndoCleanup(t *testing.T) {
	e := newInPlaceEnv(t)
	res, err, log := e.rewind("rw_1")
	if err != nil {
		t.Fatal(err, log)
	}
	if want := []string{"repo", "stop", "restore time 2026-09-24 14:04:00+00", "recover", "start", "ready"}; !slices.Equal(e.ops.calls, want) {
		t.Fatalf("steps %v, want %v", e.ops.calls, want)
	}
	if marker(e.dataDir) != "RESTORED" || e.ops.liveDir != "RESTORED" || res.RecoveredTo == nil || res.KeptUntil == nil {
		t.Fatalf("after the rewind: %q, live %q, %+v", marker(e.dataDir), e.ops.liveDir, res)
	}
	if !strings.HasPrefix(filepath.Base(res.OldDataDir), "main.before-rewind-") || marker(res.OldDataDir) != "ORIGINAL" {
		t.Fatalf("old data %s: %q", res.OldDataDir, marker(res.OldDataDir))
	}
	info, _ := os.Stat(e.dataDir)
	if info.Mode().Perm() != 0o700 {
		t.Errorf("new data directory mode %v", info.Mode())
	}
	// postgresql.auto.conf: production's current settings, older recovery
	// settings commented out, then pgBackRest's.
	auto, _ := os.ReadFile(filepath.Join(e.dataDir, "postgresql.auto.conf"))
	conf := parseConf(string(auto))
	if conf["archive_command"] != "/usr/bin/pgbackrest --stanza=app archive-push %p" || conf["archive_timeout"] != "60" ||
		!strings.Contains(conf["restore_command"], "archive-get") || conf["recovery_target_time"] != "2026-09-24 14:04:00+00" ||
		!strings.Contains(string(auto), "# Removed by Rowsafe rewind: restore_command = 'left over") {
		t.Errorf("postgresql.auto.conf:\n%s", auto)
	}
	if !strings.Contains(res.Summary, "Rewound the database to 14:04:00 UTC on 2026-09-24") || !strings.Contains(res.Summary, "kept aside until") {
		t.Errorf("summary %q", res.Summary)
	}
	states := e.a.rewindState().states()
	if len(states) != 1 || states[0].Kind != protocol.RewindKindKeptData || states[0].Status != protocol.RewindKeptBefore ||
		states[0].Expires == nil || states[0].ID != "rw_1" || states[0].Path != res.OldDataDir {
		t.Fatalf("heartbeat %+v", states)
	}

	// Cleanup refuses a recorded path that isn't a kept directory.
	must(t, e.a.rewindState().update("rw_1", func(r *rewindRecord) { r.KeptDir = e.dataDir }))
	if _, err := e.a.rewindCleanup(t.Context(), e.db, protocol.RewindCleanupParams{RewindID: "rw_1"}, &taskLog{}); err == nil ||
		!strings.Contains(err.Error(), "refusing") {
		t.Fatalf("cleanup of the live data directory: %v", err)
	}
	must(t, e.a.rewindState().update("rw_1", func(r *rewindRecord) { r.KeptDir = res.OldDataDir }))

	// Undo swaps back and keeps the rewound data aside.
	e.ops.calls = nil
	tl := &taskLog{}
	u, err := e.a.rewindUndo(t.Context(), e.db, protocol.RewindUndoParams{RewindID: "rw_1"}, tl)
	if err != nil {
		t.Fatal(err, tl.String())
	}
	if !slices.Equal(e.ops.calls, []string{"stop", "timeline", "start", "ready"}) || marker(e.dataDir) != "ORIGINAL" || e.ops.liveDir != "ORIGINAL" ||
		marker(u.RewoundDataDir) != "RESTORED" || !strings.Contains(filepath.Base(u.RewoundDataDir), "main.after-rewind-") || exists(res.OldDataDir) {
		t.Fatalf("undo: calls %v, data %q, rewound %s %q", e.ops.calls, marker(e.dataDir), u.RewoundDataDir, marker(u.RewoundDataDir))
	}
	if r, _ := e.a.rewindState().get("rw_1"); r.Status != protocol.RewindKeptAfterUndo || r.KeptDir != u.RewoundDataDir {
		t.Fatalf("after undo %+v", r)
	}
	// The timeline switch left no trace in the configuration.
	if auto, _ := os.ReadFile(filepath.Join(e.dataDir, "postgresql.auto.conf")); strings.Contains(string(auto), "recovery_target_timeline") ||
		exists(filepath.Join(e.dataDir, "recovery.signal")) {
		t.Errorf("after undo: recovery.signal %v, postgresql.auto.conf:\n%s", exists(filepath.Join(e.dataDir, "recovery.signal")), auto)
	}
	if _, err := e.a.rewindUndo(t.Context(), e.db, protocol.RewindUndoParams{RewindID: "rw_1"}, &taskLog{}); err == nil ||
		!strings.Contains(err.Error(), "already undone") {
		t.Fatalf("second undo: %v", err)
	}

	// Cleanup deletes the kept directory.
	c, err := e.a.rewindCleanup(t.Context(), e.db, protocol.RewindCleanupParams{RewindID: "rw_1"}, &taskLog{})
	if err != nil || !c.Removed || exists(u.RewoundDataDir) {
		t.Fatalf("cleanup: %+v %v", c, err)
	}
	e.original("after cleanup")
	c, err = e.a.rewindCleanup(t.Context(), e.db, protocol.RewindCleanupParams{RewindID: "rw_1"}, &taskLog{})
	if err != nil || c.Removed {
		t.Fatalf("cleanup again: %+v %v", c, err)
	}
}

// Every failure after the stop puts the original data back and starts it.
func TestRewindInPlaceRollsBack(t *testing.T) {
	for _, tc := range []struct {
		step  string
		want  string
		calls []string
	}{
		{"stop", "Nothing was changed; PostgreSQL runs as before", []string{"repo", "stop", "ready"}},
		{"restore", "while restoring the backup", []string{"repo", "stop", "restore time 2026-09-24 14:04:00+00", "start", "ready"}},
		// Once the restored data may have promoted, the original moves to a
		// new timeline before it starts again.
		{"recover", "while replaying changes", []string{"repo", "stop", "restore time 2026-09-24 14:04:00+00", "recover", "stop", "stoplocal",
			"timeline", "start", "ready"}},
		{"start", "while starting PostgreSQL", []string{"repo", "stop", "restore time 2026-09-24 14:04:00+00", "recover", "start", "timeline",
			"start", "ready"}},
		{"ready", "while starting PostgreSQL", []string{"repo", "stop", "restore time 2026-09-24 14:04:00+00", "recover", "start", "ready", "stop",
			"timeline", "start", "ready"}},
	} {
		t.Run(tc.step, func(t *testing.T) {
			e := newInPlaceEnv(t)
			e.ops.fail[tc.step] = errors.New("boom")
			e.ops.failN[tc.step] = 1
			if tc.step == "stop" {
				e.ops.fail["stop"] = errors.New("systemctl stop failed")
			}
			res, err, log := e.rewind("rw_1")
			if err == nil || !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("err = %v\n%s", err, log)
			}
			if tc.step != "stop" && (!res.RolledBack || !strings.Contains(err.Error(), "put the original data back")) {
				t.Errorf("result %+v", res)
			}
			if !slices.Equal(e.ops.calls, tc.calls) {
				t.Errorf("steps %v, want %v", e.ops.calls, tc.calls)
			}
			e.original("after the rollback")
		})
	}
}

func TestRewindInPlaceRollbackFailsThenRecoversOnRestart(t *testing.T) {
	e := newInPlaceEnv(t)
	e.ops.fail["recover"] = errors.New("recovery ended before the target was reached")
	e.ops.failN["recover"] = 1
	e.ops.fail["start"] = errors.New("systemctl start failed")
	e.ops.failN["start"] = 1
	res, err, log := e.rewind("rw_1")
	if err == nil || !strings.Contains(err.Error(), "Putting the original data back also failed") ||
		!strings.Contains(err.Error(), "No data was deleted") {
		t.Fatalf("err = %v\n%s", err, log)
	}
	if res.RolledBack {
		t.Error("reported as rolled back")
	}
	r, ok := e.a.rewindState().get("rw_1")
	if !ok || r.Status != protocol.RewindInProgress {
		t.Fatalf("record %+v", r)
	}
	// The agent restarts: the rollback runs again, and works this time.
	fresh := &Agent{cfg: e.a.cfg, log: e.a.log, rewindOps: e.ops}
	fresh.recoverRewinds(t.Context())
	e.a = fresh
	e.original("after the agent restarted")
}

// A crash in the middle (the agent killed after the restore): the next
// start rolls back by what is on disk.
func TestRewindInPlaceCrashRecovery(t *testing.T) {
	e := newInPlaceEnv(t)
	kept := e.dataDir + ".before-rewind-20260924T141000Z"
	must(t, os.Rename(e.dataDir, kept))
	must(t, os.Mkdir(e.dataDir, 0o700))
	must(t, os.WriteFile(filepath.Join(e.dataDir, "PARTIAL"), nil, 0o600))
	e.ops.live = false
	must(t, e.a.rewindState().put(rewindRecord{ID: "rw_1", Kind: protocol.RewindKindKeptData, DatabaseID: "db_1",
		Status: protocol.RewindInProgress, Phase: phaseMoved, DataDir: e.dataDir, KeptDir: kept, Database: e.db, Major: 18}))
	fresh := &Agent{cfg: e.a.cfg, log: e.a.log, rewindOps: e.ops}
	fresh.recoverRewinds(t.Context())
	e.a = fresh
	e.original("after crash recovery")

	// Interrupted before anything changed: PostgreSQL still runs, nothing
	// is stopped.
	e.ops.calls = nil
	must(t, e.a.rewindState().put(rewindRecord{ID: "rw_1", Kind: protocol.RewindKindKeptData, DatabaseID: "db_1",
		Status: protocol.RewindInProgress, Phase: phasePreflight, DataDir: e.dataDir, KeptDir: e.dataDir + ".before-rewind-20260924T141500Z",
		Database: e.db, Major: 18}))
	e.a.recoverRewinds(t.Context())
	if slices.Contains(e.ops.calls, helperStop) {
		t.Errorf("stopped a PostgreSQL that nothing had touched: %v", e.ops.calls)
	}
	e.original("after an early interruption")
}

func TestRewindUndoRollsBack(t *testing.T) {
	e := newInPlaceEnv(t)
	res, err, log := e.rewind("rw_1")
	if err != nil {
		t.Fatal(err, log)
	}
	// The move to a new timeline fails: the rewound data goes back in place.
	e.ops.fail["timeline"] = errors.New("recovery ended in an error")
	e.ops.failN["timeline"] = 1
	if u, err := e.a.rewindUndo(t.Context(), e.db, protocol.RewindUndoParams{RewindID: "rw_1"}, &taskLog{}); err == nil || !u.RolledBack ||
		!strings.Contains(err.Error(), "new timeline") {
		t.Fatalf("undo with a failing timeline switch: %+v %v", u, err)
	}
	if marker(e.dataDir) != "RESTORED" || e.ops.liveDir != "RESTORED" || marker(res.OldDataDir) != "ORIGINAL" ||
		exists(filepath.Join(res.OldDataDir, "recovery.signal")) {
		t.Fatalf("after the failed timeline switch: data %q live %q kept %q", marker(e.dataDir), e.ops.liveDir, marker(res.OldDataDir))
	}
	e.ops.fail["start"] = errors.New("systemctl start failed")
	e.ops.failN["start"] = 1
	tl := &taskLog{}
	u, err := e.a.rewindUndo(t.Context(), e.db, protocol.RewindUndoParams{RewindID: "rw_1"}, tl)
	if err == nil || !u.RolledBack || !strings.Contains(err.Error(), "put things back as they were") {
		t.Fatalf("undo: %+v %v\n%s", u, err, tl.String())
	}
	if marker(e.dataDir) != "RESTORED" || e.ops.liveDir != "RESTORED" || marker(res.OldDataDir) != "ORIGINAL" {
		t.Fatalf("after the failed undo: data %q live %q kept %q", marker(e.dataDir), e.ops.liveDir, marker(res.OldDataDir))
	}
	if r, _ := e.a.rewindState().get("rw_1"); r.Status != protocol.RewindKeptBefore || r.AsideDir != "" || r.KeptDir != res.OldDataDir {
		t.Fatalf("record %+v", r)
	}
	// And it can be undone after all.
	if _, err := e.a.rewindUndo(t.Context(), e.db, protocol.RewindUndoParams{RewindID: "rw_1"}, &taskLog{}); err != nil {
		t.Fatal(err)
	}
	if marker(e.dataDir) != "ORIGINAL" {
		t.Fatal("undo did not bring the original back")
	}
}

func TestRewindInPlacePreflightRefusals(t *testing.T) {
	for name, tc := range map[string]struct {
		setup func(e *inPlaceEnv)
		want  string
	}{
		"docker":       {func(e *inPlaceEnv) { e.a.cfg.Mode = ModeDockerSidecar }, "stop PostgreSQL's container"},
		"not allowed":  {func(e *inPlaceEnv) { os.WriteFile(e.a.cfg.RestartAllowFile, []byte("5433 x.service\n"), 0o644) }, "isn't allowed to stop PostgreSQL on port 5432"},
		"old helper":   {func(e *inPlaceEnv) { os.WriteFile(e.a.cfg.RestartHelper, []byte("#!/bin/sh\n"), 0o755) }, "Re-run the install command"},
		"no helper":    {func(e *inPlaceEnv) { os.RemoveAll(e.a.cfg.RestartDir) }, "not set up"},
		"replica":      {func(e *inPlaceEnv) { e.ops.f.InRecovery = true }, "replica"},
		"tablespaces":  {func(e *inPlaceEnv) { e.ops.f.Tablespaces = 2 }, "2 tablespaces"},
		"disk":         {func(e *inPlaceEnv) { e.ops.free = 1 << 20 }, "not enough free disk"},
		"repo":         {func(e *inPlaceEnv) { e.ops.fail["repo"] = errors.New("can't reach the backup repository") }, "backup repository"},
		"symlink data": {func(e *inPlaceEnv) { symlinkData(e) }, "symbolic link"},
		"read-only parent": {func(e *inPlaceEnv) {
			os.Chmod(filepath.Dir(e.dataDir), 0o500)
			e.t.Cleanup(func() { os.Chmod(filepath.Dir(e.dataDir), 0o700) })
		}, "can't write in"},
	} {
		t.Run(name, func(t *testing.T) {
			e := newInPlaceEnv(t)
			tc.setup(e)
			_, err, _ := e.rewind("rw_1")
			if err == nil || !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("err = %v, want %q", err, tc.want)
			}
			if slices.Contains(e.ops.calls, helperStop) {
				t.Errorf("stopped PostgreSQL after a refusal: %v", e.ops.calls)
			}
			if _, ok := e.a.rewindState().get("rw_1"); ok {
				t.Error("a refused rewind was recorded")
			}
		})
	}

	// An older helper that answers "malformed request" to stop.
	e := newInPlaceEnv(t)
	e.ops.fail["stop"] = errOldHelper
	if _, err, _ := e.rewind("rw_1"); err == nil || !errors.Is(err, errOldHelper) {
		t.Fatalf("old helper: %v", err)
	}
	e.original("after an old helper refused")

	// Bad params never get far.
	for _, p := range []protocol.RewindInPlaceParams{
		{RewindID: "../x", Target: protocol.RewindTarget{Time: &target1404}},
		{RewindID: "rw", Target: protocol.RewindTarget{}},
		{RewindID: "rw", Target: protocol.RewindTarget{Mark: "before-migration"}}, // no backup set
		{RewindID: "rw", Target: protocol.RewindTarget{Mark: "x'; drop", BackupSet: "20260924-010000F"}},
		{RewindID: "rw", Target: protocol.RewindTarget{Time: &target1404, BackupSet: "--delta"}},
	} {
		if _, err := e.a.rewindInPlace(t.Context(), e.db, p, &taskLog{}); err == nil {
			t.Errorf("accepted %+v", p)
		}
	}
	if len(e.ops.calls) > 2 {
		t.Errorf("bad params reached the steps: %v", e.ops.calls)
	}
}

func symlinkData(e *inPlaceEnv) {
	real := e.dataDir + "-real"
	os.Rename(e.dataDir, real)
	os.Symlink(real, e.dataDir)
}

func TestMergeAutoConf(t *testing.T) {
	current := "# Do not edit this file manually!\narchive_mode = 'on'\nRestore_Command = 'old'\nrecovery_target_time = 'x'\nwork_mem = '64MB'"
	restored := "archive_mode = 'on'\n\n" + pgbackrestRecoveryHeader + " on 2026\nrestore_command = 'new'\n"
	got, ok := mergeAutoConf(current, restored)
	if !ok {
		t.Fatal("no block found")
	}
	conf := parseConf(got)
	if conf["restore_command"] != "new" || conf["work_mem"] != "64MB" || conf["recovery_target_time"] != "" {
		t.Errorf("merged:\n%s", got)
	}
	if _, ok := mergeAutoConf(current, "archive_mode = 'on'\n"); ok {
		t.Error("a restore without pgBackRest's block must be left alone")
	}
}

func TestValidKeptDir(t *testing.T) {
	root := t.TempDir()
	data := filepath.Join(root, "main")
	os.Mkdir(data, 0o700)
	good := data + ".before-rewind-20260924T140400Z"
	os.Mkdir(good, 0o700)
	if err := validKeptDir(data, good); err != nil {
		t.Fatal(err)
	}
	for _, bad := range []string{data, filepath.Join(root, "other.before-rewind-20260924T140400Z"), data + ".before-rewind-x",
		filepath.Join(root, "sub", "main.before-rewind-20260924T140400Z"), "/", root} {
		if err := validKeptDir(data, bad); err == nil {
			t.Errorf("accepted %s", bad)
		}
	}
	link := data + ".after-rewind-20260924T140400Z"
	os.Symlink(good, link)
	if err := validKeptDir(data, link); err == nil {
		t.Error("accepted a symlink")
	}
}

// askHelper speaks both request forms and recognises an old helper.
func TestAskHelper(t *testing.T) {
	oldPoll, oldHelper := restartPoll, restartHelperTimeout
	defer func() { restartPoll, restartHelperTimeout = oldPoll, oldHelper }()
	restartPoll, restartHelperTimeout = 5*time.Millisecond, 2*time.Second
	root := t.TempDir()
	dir, out := filepath.Join(root, "restart"), filepath.Join(root, "run")
	os.Mkdir(dir, 0o700)
	os.Mkdir(out, 0o755)
	a := &Agent{cfg: Config{RestartDir: dir, RestartResultDir: out}, log: slog.New(slog.DiscardHandler)}
	answer := func(reply func(fields []string) string) chan string {
		got := make(chan string, 1)
		go func() {
			for range 400 {
				data, err := os.ReadFile(filepath.Join(dir, "request"))
				if err == nil {
					os.Remove(filepath.Join(dir, "request"))
					got <- strings.TrimSpace(string(data))
					os.WriteFile(filepath.Join(out, "r.tmp"), []byte(reply(strings.Fields(string(data)))), 0o644)
					os.Rename(filepath.Join(out, "r.tmp"), filepath.Join(out, "result"))
					return
				}
				time.Sleep(5 * time.Millisecond)
			}
		}()
		return got
	}
	got := answer(func(f []string) string { return "id=" + f[0] + "\naction=stop\nok=1\n" })
	if res, err := a.askHelper(t.Context(), helperStop, 5432, "rw_1-stop"); err != nil || res["ok"] != "1" || <-got != "rw_1-stop stop 5432" {
		t.Fatalf("stop: %v %v", res, err)
	}
	got = answer(func(f []string) string { return "id=" + f[0] + "\nok=1\n" })
	if _, err := a.askHelper(t.Context(), helperRestart, 5432, "task_1"); err != nil || <-got != "task_1 5432" {
		t.Fatalf("restart uses the old form: %v", err)
	}
	got = answer(func(f []string) string { return "id=" + f[0] + "\nok=0\nerror=malformed request\n" })
	if _, err := a.askHelper(t.Context(), helperStart, 5432, "rw_1-start"); !errors.Is(err, errOldHelper) ||
		!strings.Contains(err.Error(), "Re-run the install command") {
		t.Fatalf("old helper: %v", err)
	}
	<-got

	// The heartbeat says what the installed helper can do.
	allow := filepath.Join(root, "allow")
	os.WriteFile(allow, []byte("5432 postgresql@18-main.service\n"), 0o644)
	helper := filepath.Join(root, "helper")
	a.cfg.RestartAllowFile, a.cfg.RestartHelper = allow, helper
	os.WriteFile(helper, []byte("#!/bin/sh\n# The agent reads the next line to know what this helper can do.\n# actions: restart stop start\n"), 0o755)
	if acts := a.helperActions(); !slices.Equal(acts, []string{"restart", "stop", "start"}) {
		t.Errorf("actions %v", acts)
	}
	os.WriteFile(helper, []byte("#!/bin/sh\n"), 0o755)
	if acts := a.helperActions(); !slices.Equal(acts, []string{"restart"}) {
		t.Errorf("old helper actions %v", acts)
	}
	a.cfg.Mode = ModeDockerSidecar
	if acts := a.helperActions(); acts != nil {
		t.Errorf("sidecar actions %v", acts)
	}
}

func TestRewindStateExpiryAndHeartbeat(t *testing.T) {
	root := t.TempDir()
	a := &Agent{cfg: Config{StateDir: root, RewindDir: filepath.Join(root, "rewind"), PGBinDir: "/nonexistent/%d"},
		log: slog.New(slog.DiscardHandler), runner: &fakeRunner{}}
	now := time.Now().UTC()
	st := a.rewindState()
	copyDir := filepath.Join(a.cfg.RewindDir, "cp_1")
	must(t, os.MkdirAll(filepath.Join(copyDir, "data"), 0o700))
	must(t, os.WriteFile(filepath.Join(copyDir, copyMarker), []byte("cp_1\n"), 0o600))
	must(t, st.put(rewindRecord{ID: "cp_1", Kind: protocol.RewindKindCopy, DatabaseID: "db_1", Status: protocol.RewindCopyReady,
		CreatedAt: now, Expires: now.Add(time.Hour), Dir: copyDir, Major: 18, SizeBytes: 42}))

	// Persisted: a restarted agent knows it.
	b := &Agent{cfg: a.cfg, log: a.log, runner: a.runner}
	if r, ok := b.rewindState().get("cp_1"); !ok || r.SizeBytes != 42 {
		t.Fatalf("reloaded %+v", r)
	}
	hb := b.rewindState().states()
	if len(hb) != 1 || hb[0].Kind != protocol.RewindKindCopy || hb[0].Status != protocol.RewindCopyReady || hb[0].Expires == nil {
		t.Fatalf("heartbeat %+v", hb)
	}
	// Extend from the control plane, clamped to 7 days; a past expiry is ignored.
	b.rewindState().setExpiries([]protocol.RewindExpiry{{ID: "cp_1", Expires: now.Add(30 * 24 * time.Hour)}, {ID: "nope", Expires: now}}, now)
	if r, _ := b.rewindState().get("cp_1"); !r.Expires.Equal(now.Add(maxCopyLifetime)) {
		t.Errorf("clamped expiry %v", r.Expires)
	}
	b.rewindState().setExpiries([]protocol.RewindExpiry{{ID: "cp_1", Expires: now.Add(-time.Hour)}}, now)
	if r, _ := b.rewindState().get("cp_1"); !r.Expires.Equal(now.Add(maxCopyLifetime)) {
		t.Errorf("a past expiry was applied: %v", r.Expires)
	}
	// Not expired yet: kept. Expired: removed with its directory, no
	// control plane needed.
	b.expireRewinds(now.Add(time.Hour))
	if !exists(copyDir) {
		t.Fatal("removed before it expired")
	}
	b.expireRewinds(now.Add(8 * 24 * time.Hour))
	if exists(copyDir) {
		t.Fatal("an expired copy is still there")
	}
	if _, ok := b.rewindState().get("cp_1"); ok || len(b.rewindState().states()) != 0 {
		t.Fatal("an expired copy is still recorded")
	}

	// Copy expiry defaults and limits.
	if got := copyExpiry(time.Time{}, now); !got.Equal(now.Add(24 * time.Hour)) {
		t.Errorf("default %v", got)
	}
	if got := copyExpiry(now.Add(-time.Hour), now); !got.Equal(now.Add(time.Hour)) {
		t.Errorf("past %v", got)
	}
	if got := copyExpiry(now.Add(30*24*time.Hour), now); !got.Equal(now.Add(7 * 24 * time.Hour)) {
		t.Errorf("too long %v", got)
	}
}

func TestStaleCopiesAndDrop(t *testing.T) {
	root := t.TempDir()
	a := &Agent{cfg: Config{StateDir: root, RewindDir: filepath.Join(root, "rewind"), PGBinDir: "/nonexistent/%d"},
		log: slog.New(slog.DiscardHandler), runner: &fakeRunner{}}
	mk := func(name string, withMarker bool) string {
		d := filepath.Join(a.cfg.RewindDir, name)
		must(t, os.MkdirAll(filepath.Join(d, "data"), 0o700))
		if withMarker {
			must(t, os.WriteFile(filepath.Join(d, copyMarker), []byte(name), 0o600))
		}
		return d
	}
	stale := mk("cp_stale", true)
	foreign := mk("keepme", false)
	known := mk("cp_known", true)
	// A copy whose restore was interrupted, and a leftover nobody knows.
	must(t, a.rewindState().put(rewindRecord{ID: "cp_known", Kind: protocol.RewindKindCopy, DatabaseID: "db_1",
		Status: protocol.RewindCopyRestoring, Dir: known, CreatedAt: time.Now()}))
	a.recoverRewinds(t.Context())
	if exists(stale) || exists(known) || !exists(foreign) {
		t.Fatalf("stale %v known %v foreign %v", exists(stale), exists(known), exists(foreign))
	}
	if len(a.rewindState().all()) != 0 {
		t.Fatal("interrupted copy still recorded")
	}

	// Drop: unknown copy, another database's copy, a symlinked directory.
	db := protocol.DatabaseSpec{ID: "db_1"}
	res, err := a.rewindDrop(t.Context(), db, protocol.RewindDropParams{CopyID: "cp_gone"}, &taskLog{})
	if err != nil || res.Removed {
		t.Fatalf("unknown: %+v %v", res, err)
	}
	other := mk("cp_other", true)
	must(t, a.rewindState().put(rewindRecord{ID: "cp_other", Kind: protocol.RewindKindCopy, DatabaseID: "db_2",
		Status: protocol.RewindCopyReady, Dir: other, CreatedAt: time.Now()}))
	if _, err := a.rewindDrop(t.Context(), db, protocol.RewindDropParams{CopyID: "cp_other"}, &taskLog{}); err == nil {
		t.Fatal("dropped another database's copy")
	}
	victim := filepath.Join(root, "victim")
	must(t, os.MkdirAll(victim, 0o700))
	must(t, os.WriteFile(filepath.Join(victim, copyMarker), nil, 0o600))
	link := filepath.Join(a.cfg.RewindDir, "cp_link")
	must(t, os.Symlink(victim, link))
	must(t, a.rewindState().put(rewindRecord{ID: "cp_link", Kind: protocol.RewindKindCopy, DatabaseID: "db_1",
		Status: protocol.RewindCopyReady, Dir: link, CreatedAt: time.Now()}))
	if _, err := a.rewindDrop(t.Context(), db, protocol.RewindDropParams{CopyID: "cp_link"}, &taskLog{}); err == nil || !exists(victim) {
		t.Fatalf("followed a symlink: %v", err)
	}
	// A record pointing outside the rewind directory is refused too.
	must(t, a.rewindState().put(rewindRecord{ID: "cp_out", Kind: protocol.RewindKindCopy, DatabaseID: "db_1",
		Status: protocol.RewindCopyReady, Dir: victim, CreatedAt: time.Now()}))
	if _, err := a.rewindDrop(t.Context(), db, protocol.RewindDropParams{CopyID: "cp_out"}, &taskLog{}); err == nil || !exists(victim) {
		t.Fatalf("removed a directory outside the rewind directory: %v", err)
	}
	// One copy per database.
	a.rewindState().remove("cp_link")
	a.rewindState().remove("cp_out")
	must(t, a.rewindState().put(rewindRecord{ID: "cp_2", Kind: protocol.RewindKindCopy, DatabaseID: "db_1",
		Status: protocol.RewindCopyReady, Dir: mk("cp_2", true), CreatedAt: time.Now()}))
	now := time.Now().Add(-time.Hour)
	_, err = a.rewindCopy(t.Context(), protocol.DatabaseSpec{ID: "db_1", Name: "shop"},
		protocol.RewindCopyParams{CopyID: "cp_3", Target: protocol.RewindTarget{Time: &now}}, &taskLog{})
	if err == nil || !strings.Contains(err.Error(), "one copy per database") {
		t.Fatalf("second copy: %v", err)
	}
}

func TestRewindRestoreArgs(t *testing.T) {
	past := time.Date(2026, 9, 24, 14, 4, 5, 123456000, time.FixedZone("CEST", 2*3600))
	typ, target, set, err := rewindRestoreArgs(protocol.RewindTarget{Time: &past})
	if err != nil || typ != "time" || target != "2026-09-24 12:04:05.123456+00" || set != "" {
		t.Errorf("time: %s %s %s %v", typ, target, set, err)
	}
	typ, target, set, err = rewindRestoreArgs(protocol.RewindTarget{Mark: "before-migration", BackupSet: "20260920-010002F_20260921-010003D"})
	if err != nil || typ != "name" || target != "before-migration" || set != "20260920-010002F_20260921-010003D" {
		t.Errorf("mark: %s %s %s %v", typ, target, set, err)
	}
	future := time.Now().Add(time.Hour)
	for _, bad := range []protocol.RewindTarget{
		{}, {Time: &past, Mark: "m"}, {Time: &future}, {Mark: "m"}, {Mark: "Bad Name", BackupSet: "20260920-010002F"},
	} {
		if _, _, _, err := rewindRestoreArgs(bad); err == nil {
			t.Errorf("accepted %+v", bad)
		}
	}
}
