package collect

import (
	"context"
	"slices"
	"strings"
	"testing"
	"time"

	"github.com/rowsafe/rowsafe/protocol"
)

// TestAdvisorFactsLocalPostgres runs the advisor readings against a
// crafted schema: a foreign key without an index, tables without a primary
// key, integer keys near their maximum, a sequence behind its column, an
// invalid index from a failed concurrent build, duplicate constraints and
// a large insert-only table.
func TestAdvisorFactsLocalPostgres(t *testing.T) {
	tg := localTarget(t)
	name, conn := scratchDB(t, tg)
	for _, sql := range []string{
		`CREATE TABLE customers (id serial PRIMARY KEY, name text)`,
		`INSERT INTO customers (name) SELECT 'c' || g FROM generate_series(1, 100) g`,
		`CREATE TABLE orders (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_id int NOT NULL REFERENCES customers, total int)`,
		`INSERT INTO orders (customer_id, total) SELECT 1 + g % 100, g FROM generate_series(1, 20000) g`,
		// Indexed foreign key: not reported.
		`CREATE TABLE payments (id bigserial PRIMARY KEY, order_id int REFERENCES orders)`,
		`CREATE INDEX payments_order ON payments (order_id)`,
		// No primary key, timestamp without time zone, with writes.
		`CREATE TABLE events (at timestamp NOT NULL DEFAULT now(), payload text)`,
		`INSERT INTO events (payload) SELECT 'e' FROM generate_series(1, 50) g`,
		// A unique NOT NULL column counts as a key: not reported.
		`CREATE TABLE tags (name text NOT NULL UNIQUE)`,
		// An integer serial at 93%, and an integer foreign key to it.
		`CREATE TABLE tickets (id serial PRIMARY KEY)`,
		`SELECT setval('tickets_id_seq', 2000000000)`,
		`CREATE TABLE ticket_notes (id bigserial PRIMARY KEY, ticket_id int REFERENCES tickets)`,
		`CREATE INDEX ticket_notes_ticket ON ticket_notes (ticket_id)`,
		// A bigint column whose sequence only goes up to the integer maximum.
		`CREATE SEQUENCE widget_seq AS integer`,
		`CREATE TABLE widgets (id bigint PRIMARY KEY DEFAULT nextval('widget_seq'))`,
		`SELECT setval('widget_seq', 1500000000)`,
		// Rows copied in with explicit ids: the sequence is behind.
		`CREATE TABLE items (id serial PRIMARY KEY, label text)`,
		`INSERT INTO items (id, label) VALUES (1, 'a'), (2, 'b'), (50, 'c')`,
		// Duplicate constraints.
		`CREATE TABLE accounts (id int PRIMARY KEY, email text,
		   CONSTRAINT accounts_email_key UNIQUE (email), CONSTRAINT accounts_id_email UNIQUE (id, email),
		   CONSTRAINT accounts_id_positive CHECK (id > 0), CONSTRAINT accounts_id_positive2 CHECK (id > 0))`,
		// (CREATE TABLE merges identical unique constraints; ALTER TABLE doesn't.)
		`ALTER TABLE accounts ADD CONSTRAINT accounts_email_again UNIQUE (email)`,
		// A failed concurrent unique index build leaves an invalid index.
		`CREATE TABLE dupes (v int)`,
		`INSERT INTO dupes VALUES (1), (1)`,
		// A large insert-only table with a time column.
		`CREATE TABLE readings (id bigserial PRIMARY KEY, taken_at timestamptz NOT NULL DEFAULT now(), v int)`,
		`INSERT INTO readings (v) SELECT g FROM generate_series(1, 1000001) g`,
		`CREATE INDEX readings_taken ON readings (taken_at)`,
		`ANALYZE`,
	} {
		if _, err := conn.Exec(t.Context(), sql); err != nil {
			t.Fatalf("%s: %v", sql, err)
		}
	}
	if _, err := conn.Exec(t.Context(), `CREATE UNIQUE INDEX CONCURRENTLY dupes_v ON dupes (v)`); err == nil {
		t.Fatal("building a unique index over duplicates succeeded")
	}
	_, _ = conn.Exec(t.Context(), `SELECT pg_stat_force_next_flush()`)
	_, _ = conn.Exec(t.Context(), `SELECT 1`)
	time.Sleep(200 * time.Millisecond)

	ins := &protocol.Insights{}
	pg, err := tg.insightsConnect(t.Context(), "postgres")
	if err != nil {
		t.Fatal(err)
	}
	advisorCluster(t.Context(), pg, ins)
	pg.Close(context.Background())
	if ins.Advisor == nil || ins.Advisor.Memory == nil || ins.Advisor.Memory.SharedBuffersBytes <= 0 || ins.Advisor.Memory.MaxConnections <= 0 {
		t.Fatalf("memory facts = %+v (notes %v)", ins.Advisor, ins.Notes)
	}
	dbc, err := tg.insightsConnect(t.Context(), name)
	if err != nil {
		t.Fatal(err)
	}
	defer dbc.Close(context.Background())
	q := insightQueries{conn: dbc, db: name}
	for _, c := range q.advisorChecks(ins, false, nil) {
		if err := c.fn(t.Context()); err != nil {
			t.Errorf("%s: %v", c.what, err)
		}
	}
	sortAndCapAdvisor(ins)
	a := ins.Advisor

	var fks []string
	for _, x := range a.ForeignKeys {
		fks = append(fks, x.Table+"("+strings.Join(x.Columns, ",")+")->"+x.RefTable)
		if x.Table == "orders" && (x.RowsEstimate < 10000 || x.TableBytes == 0 || x.Constraint == "") {
			t.Errorf("orders foreign key facts = %+v", x)
		}
	}
	if !slices.Contains(fks, "orders(customer_id)->customers") || slices.Contains(fks, "payments(order_id)->orders") ||
		slices.Contains(fks, "ticket_notes(ticket_id)->tickets") {
		t.Errorf("foreign keys without index = %v", fks)
	}

	var nopk []string
	for _, x := range a.NoPrimaryKey {
		nopk = append(nopk, x.Table)
	}
	if !slices.Contains(nopk, "events") || !slices.Contains(nopk, "dupes") || slices.Contains(nopk, "tags") || slices.Contains(nopk, "orders") {
		t.Errorf("tables without a primary key = %v", nopk)
	}

	keys := map[string]protocol.IntegerKey{}
	for _, x := range a.IntegerKeys {
		keys[x.Kind+":"+x.Table+"."+x.Column] = x
	}
	if k, ok := keys["column:tickets.id"]; !ok || k.UsedPct < 90 || k.MaxValue != 2147483647 || k.Sequence != "public.tickets_id_seq" || k.ColumnType != "integer" {
		t.Errorf("tickets.id = %+v (all %v)", k, keys)
	}
	if k, ok := keys["foreign_key:ticket_notes.ticket_id"]; !ok || k.References != "public.tickets.id" || k.UsedPct < 90 {
		t.Errorf("ticket_notes.ticket_id = %+v", k)
	}
	if k, ok := keys["sequence:widgets.id"]; !ok || k.ColumnType != "bigint" || k.MaxValue != 2147483647 || k.UsedPct < 69 {
		t.Errorf("widgets.id = %+v", k)
	}
	if _, ok := keys["column:orders.id"]; ok {
		t.Error("orders.id (a few thousand of 2 billion) reported")
	}

	var behind []string
	for _, x := range a.SequencesBehind {
		behind = append(behind, x.Table+"."+x.Column)
		if x.Table == "items" && (x.MaxInColumn != 50 || x.Sequence != "items_id_seq") {
			t.Errorf("items sequence = %+v", x)
		}
	}
	if !slices.Contains(behind, "items.id") || slices.Contains(behind, "orders.id") || slices.Contains(behind, "customers.id") {
		t.Errorf("sequences behind = %v", behind)
	}

	if len(a.InvalidIndexes) != 1 || a.InvalidIndexes[0].Index != "dupes_v" || !strings.Contains(a.InvalidIndexes[0].Definition, "UNIQUE") {
		t.Errorf("invalid indexes = %+v", a.InvalidIndexes)
	}

	dc := map[string]string{}
	for _, x := range a.DuplicateConstraints {
		dc[x.Constraint] = x.Type + ":" + x.Kind + ":" + x.CoveredBy
	}
	if dc["accounts_email_again"] != "unique:duplicate:accounts_email_key" || dc["accounts_id_email"] == "" ||
		dc["accounts_id_positive2"] != "check:duplicate:accounts_id_positive" || dc["accounts_email_key"] != "" {
		t.Errorf("duplicate constraints = %v", dc)
	}

	var ts []string
	for _, x := range a.TimestampColumns {
		ts = append(ts, x.Table+"("+strings.Join(x.Columns, ",")+")")
	}
	if !slices.Contains(ts, "events(at)") {
		t.Errorf("timestamp columns = %v", ts)
	}

	var big *protocol.LargeTable
	for i := range a.LargeTables {
		if a.LargeTables[i].Table == "readings" {
			big = &a.LargeTables[i]
		}
	}
	if big == nil || big.RowsEstimate < 1_000_000 || big.Inserts < 1_000_000 || big.TimeColumn != "taken_at" || !big.TimeIndexed || big.Partitioned {
		t.Errorf("readings = %+v (all %+v)", big, a.LargeTables)
	}
}
